name: valorant_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  # hive no sql database
  hive: ^2.2.3
  hive_generator: ^2.0.1
  hive_flutter: ^1.1.0
  # path
  path_provider: ^2.1.1
  # get it singleton
  get_it: ^7.6.4
  # async
  async: ^2.11.0
  # equatable
  equatable: ^2.0.5
  # state manager
  flutter_bloc: ^8.1.3
  # interceptor
  dio: ^5.3.3
  dio_retry_plus: ^2.0.3
  # internet check
  internet_connection_checker: ^1.0.0+1
  # chuck
  chuck_interceptor: ^2.0.5
  # box
  gap: ^3.0.1
  # svg render
  flutter_svg: ^2.0.7
  # dropdown
  dropdown_button2: ^2.3.9
  # cached image
  cached_network_image: ^3.3.0
  # native splash
  flutter_native_splash: ^2.3.3
  # firebase
  firebase_core: ^2.17.0
  firebase_analytics: ^10.5.1
  firebase_messaging: ^14.6.9
  firebase_crashlytics: ^3.3.7
  firebase_performance: ^0.9.2+7
  # local notification
  flutter_local_notifications: ^16.3.2
  # router
  go_router: ^13.2.0
  #zoom tap
  zoom_tap_animation: ^1.1.0
  #animation
  animate_do: ^3.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  hive_generator: ^2.0.1
  build_runner: ^2.4.6
  bloc_test: ^9.1.4



flutter:
  uses-material-design: true

  assets:
    - assets/locale/
    - assets/fonts/
    - assets/images/
    - assets/icons/
  fonts:
    - family: AppIcons
      fonts:
        - asset: assets/fonts/AppIcons.ttf


    - family: Bowlby One SC
      fonts:
        - asset: assets/fonts/Bowlby/BowlbyOneSC-Regular.ttf